
# We need to update the sentence tokenizer to add some extra abbreviations
# https://www.wikilengua.org/index.php/Lista_de_abreviaturas_de_v%C3%ADas
set_base_nltk_abbv_spanish = {
    '?í',
    'a.d.n',
    'aa',
    'ajo',
    'ají',
    'ale',
    'alh',
    'aps',
    'arg',
    'at',
    'ath',
    'atl',
    'avda',
    'c',
    'cc',
    'cc.oo',
    'ch',
    'd',
    'd.a',
    'dgt',
    'dr',
    'ea_',
    'ee.uu',
    'esc',
    'esp',
    'etc',
    'f',
    'f.l',
    'g',
    'h',
    'ing',
    'inh',
    'j',
    'j.c.n.ll',
    'j.d',
    'j.t',
    'jn',
    'k',
    'k.a',
    'kas',
    'l',
    'lea',
    'lit',
    'll',
    'm',
    'm.c',
    'mt',
    'n',
    'oo',
    'p',
    'r',
    'res',
    's',
    's.a',
    's.o.s',
    'sr',
    'ss',
    't',
    'u.p',
    'uu',
    'vv',
    'w',
    'w.o',
    'z',
    'zim',
    'íes'
}

# IMPORTANT! KEYS HAVE TO BE ALL UNDERSCORE, DO NOT CAPITALIZE EVEN IF ABBV IS CAPITALIZED! OTHERWISE IT WONT WORK
d_spanish_abbv = {
    'tfno.': 'teléfono',
    'tel.': 'teléfono',
    'teléf.': 'teléfono',
    'tf.': 'teléfono',
    'tl.': 'teléfono',
    'ud.': 'usted',
    'vd.': 'usted',
    'sr.': 'señor',
    'sra.': 'señora',
    'pl.': 'plaza',
    'pla.': 'plaza',
    'plz.': 'plaza',
    'plza.': 'plaza',
    'c.p.': 'código postal',
    'cp.': 'código postal',
    'bl.': 'bloque',
    'bj.': 'bajo',
    'Av.': 'avenida',
    'av.': 'avenida',
    'avda.': 'avenida',
    'avd.': 'avenida',
    'avnd.': 'avenida',
    'avn.': 'avenida',
    'avin.': 'avenida',
    'aving.': 'avenida',
    'avngd.': 'avenida',
    'aj.': 'ayuntamiento(?)',
    'ay.': 'ayuntamiento',
    'ayto.': 'ayuntamiento',
    'aytm.': 'ayuntamiento',
    'rr.': 'arroyo',
    'b.': 'barrio',
    'blvr.': 'bulevar',
    'c.': 'calle',
    'c/': 'calle',
    'cl.': 'calle',
    'call.': 'callejón',
    'camp.': 'campillo',
    'carr.': 'carrera',
    'ctra.': 'carretera',
    'carret.': 'carretera',
    'cerr.': 'cerrillo',
    'cost.': 'costanilla',
    'cta.': 'cuesta',
    'ens.': 'ensanche',
    'extr.': 'extrarradio',
    'gta.': 'glorieta',
    'int.': 'interior',
    'pje.': 'pasaje',
    'prad.': 'pradera',
    'pret.': 'pretil',
    'pte.': 'puente',
    'rbla.': 'rambla',
    'rib.': 'ribera',
    'rda.': 'ronda',
    'tr.': 'travesía',
    'vda.': 'vereda',
    'D.N.I.': '',
    'Sres.': '',
    'Vds.': '',
    'Uds.': '',
    'art.': '',
    'Udes.': '',
    'ref.': '',
    'ATT.': '',
    'atte.': '',
    # 'No.': '',
    'cta.': '',
    'Da.': '',
    'Ldo.': '',
    'Esc.': 'escalera',
    'num.': 'numero',
    'dr.': 'doctor',
    'dra.': 'doctora',
    'd.': 'don', 
    'da.': 'doña',
    'nac.': 'nacimiento',
    'D/ña.': '',
}


d_spanish_abbv_lower = {k.lower():v.lower() for k,v in d_spanish_abbv.items()}


# # Won't be used for now...
# d_spanish_abbv_case_sensitive = {
#     'SA.': 'Sociedad Anónima',
#     'S.A.': 'Sociedad Anónima',
#     # ...
# }